<template>
  <div class="spinner">
    <div class="spinner-wrap">
      <div :class="spinnerColor"></div>
    </div>
  </div>
</template>

<script setup>

const props = defineProps({
  white: {
    type: Boolean,
    default: false,
  }
});

const spinnerColor = computed(() => {
  return (
        props.white
        ? 'border-white'
        : 'border-blue-600'
    );
});

</script>

<style lang="scss" scoped>
@keyframes spinner-wrap {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }

  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}

.spinner-wrap div {
  position: absolute;
  width: 1rem;
  height: 1rem;
  border-width: 0.3rem;
  border-top-color: transparent;
  border-radius: 50%;
}

.spinner-wrap div {
  animation: spinner-wrap 1s linear infinite;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.spinner {
  width: 2rem;
  height: 2rem;
  display: inline-block;
  overflow: hidden;
  background: none;
}

.spinner-wrap {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.spinner-wrap div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>